
export const ORGANIZATION_REQUIST='ORGANIZATION_REQUIST'
export const GET_ORGANIZATION='GET_ORGANIZATION'
export const CREATE_ORGANIZATION='CREATE_ORGANIZATION'
export const ORGANIZATION_FAILD='ORGANIZATION_FAILD'
export  const CLEAR_ERROR="CLEAR_ERROR"
export  const ORGANIZATION_SUCCESS="ORGANIZATION_SUCCESS"