

export const SCHOOLOREGISTRATION_REQUEST = 'SCHOOLOREGISTRATION_REQUEST';
export const SCHOOLOREGISTRATION_SUCCESS = 'SCHOOLOREGISTRATION_SUCCESS';
export const SCHOOLOREGISTRATION_FAILURE = 'SCHOOLOREGISTRATION_FAILURE';

export const STATE_LIST_REQUEST="STATE_LIST_REQUEST"
export const STATE_LIST_SUCCESS="STATE_LIST_SUCCESS"
export const STATE_LIST_FAILURE="STATE_LIST_FAILURE"

export const CITY_LIST_REQUEST="CITY_LIST_REQUEST"
export const CITY_LIST_SUCCESS="CITY_LIST_SUCCESS"
export const CITY_LIST_FAILURE="CITY_LIST_FAILURE"

// actionTypes.js
export const CREATE_SCHOOLREG_REQUEST = 'CREATE_SCHOOLREG_REQUEST';
export const CREATE_SCHOOLREG_SUCCESS = 'CREATE_SCHOOLREG_SUCCESS';
export const CREATE_SCHOOLREG_FAILURE = 'CREATE_SCHOOLREG_FAILURE';


export const DELETE_SCHOOLREG_REQUEST = 'DELETE_SCHOOLREG_REQUEST';
export const DELETE_SCHOOLREG_SUCCESS = 'DELETE_SCHOOLREG_SUCCESS';
export const DELETE_SCHOOLREG_FAILURE = 'DELETE_SCHOOLREG_FAILURE';


